session_name: ethereum
windows:
- window_name: ethstats:3000
  layout: tiled
  shell_command_before:
    - cd eth-netstats                    # run as a first command in all panes
  panes:
    - shell_command:
        - grunt all
        - WS_SECRET=superAgente86 npm start 
