session_name: ethereum
windows:
- window_name: nodos
  layout: tiled
  shell_command_before:
    - cd ~/ethereum/                 # run as a first command in all panes
  panes:
    - shell_command:           # pane no. 1
        - echo hola
        #--rpccorsdomain: for the explorer
        #--rpcaddr "0.0.0.0": for metamask

    - shell_command:
        - echo hola
- window_name: explorer:8000
  layout: tiled
  shell_command_before:
    - echo start                    # run as a first command in all panes
  panes:
    - shell_command:
        - cd explorer
        - npm start
- window_name: ethstats
  layout: tiled
  shell_command_before:
    - echo start                    # run as a first command in all panes
  panes:
    - shell_command:
        - cd eth-net-intelligence-api
        - pm2 start app.json


