session_name: ethereum
windows:
- window_name: nodos
  layout: tiled
  shell_command_before:
    - cd ~/ethereum/                 # run as a first command in all panes
  panes:
    - shell_command:           # pane no. 1
        - geth --rpc --rpcport 8545 --port 30803 --networkid 22 --datadir="./node" --ipcpath="geth.ipc"  --rpcaddr "0.0.0.0" --rpccorsdomain "*"
        #--rpccorsdomain: for the explorer
        #--rpcaddr "0.0.0.0": for metamask

    - shell_command:
        - sleep 3
        - echo "admin.nodeInfo.enode" | geth attach ipc:./node/geth.ipc > share2/nodeinfo.txt
        - geth attach ipc:./node/geth.ipc 
        - personal.newAccount("asd")
        - miner.start(1); admin.sleepBlocks(5); miner.stop()
        - personal.listAccounts
- window_name: explorer:8000
  layout: tiled
  shell_command_before:
    - echo start                    # run as a first command in all panes
  panes:
    - shell_command:
        - cd explorer
        - npm start
- window_name: ethstats
  layout: tiled
  shell_command_before:
    - echo start                    # run as a first command in all panes
  panes:
    - shell_command:
        - cd eth-net-intelligence-api
        - pm2 start app.json


