#1-2.
FROM docker_pow:latest 
MAINTAINER Lean <leandro.rawicz@coinfabrik.com>
# run rm -rf config.yaml
COPY config.yaml config.yaml
COPY start.sh start.sh
RUN chmod +x start.sh
#CMD ./start.sh
#CMD bash
